# .graphclientrc.yml
sources:
  - name: uniswapv3
    handler:
      graphql:
        endpoint: "{context.uniswapv3url:https://gateway.thegraph.com/api/${API_KEY}/subgraphs/id/FbCGRftH4a3yZugY7TnbYgPJVEv2LvMT6oF1fxPe9aJM}"
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
documents:
  - ./src/graphql/GetAllPools.gql
